### ISSUE TITLE
Thanks a lot for creating this app! (not an issue)

### ISSUE THREAD

**Issue by alpha4041** [justdeko/piley#154]
Thanks a lot of creating this app, I found it really useful for me.
I also posted it on [popMODS](https://t.me/popmods/), hoping that other people will find it good and useful!

**Comment by justdeko** [comment]
Hi @alpha4041 , thanks for the shout-out! Happy that you like the app, I'm currently finishing up the last changes for v0.6, so that's coming soon :)
